name: Build Android APK with Buildozer

on:
  push:
  pull_request:

jobs:
  build-apk:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libtool \
            libffi-dev \
            python3-pip \
            build-essential \
            autoconf \
            pkg-config \
            zlib1g-dev \
            libncurses6 \
            libncursesw6 \
            libtinfo6 \
            openjdk-17-jdk \
            git \
            unzip \
            wget \
            zip

      - name: Install Buildozer
        run: |
          python3 -m pip install --upgrade pip
          pip install buildozer

      - name: Create buildozer.spec if not exists
        run: |
          if [ ! -f buildozer.spec ]; then
            buildozer init
          fi

      - name: Accept Android SDK licenses and install SDK
        run: |
          mkdir -p $HOME/android-sdk/cmdline-tools
          cd $HOME/android-sdk/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O tools.zip
          unzip -q tools.zip
          rm tools.zip
          mv cmdline-tools latest
          yes | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=$HOME/android-sdk --licenses
          $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=$HOME/android-sdk \
            "platform-tools" \
            "platforms;android-33" \
            "build-tools;33.0.0"

      - name: Set environment variables
        run: |
          echo "ANDROIDSDK=$HOME/android-sdk" >> $GITHUB_ENV
          echo "$HOME/.local/bin:$PATH" >> $GITHUB_PATH

      - name: Build APK with Buildozer
        run: |
          buildozer android debug

      - name: List APKs
        run: ls -lh bin || true

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: slotprediksnapp-apk
          path: bin/*.apk
